version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my-store
      - POSTGRES_USER=gerardoisc
      - POSTGRES_PASSWORD=The-most-secure-password
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data