version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my-store
      - POSTGRES_USER=gerardoisc
      - POSTGRES_PASSWORD=The-most-secure-password
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=The-other-secure-password
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my-store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=The-most-secure-password
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql #PMA_host -> service name of the ddbb.
      - MYSQL_ROOT_PASSWORD=The-most-secure-password
    ports:
      - 3309:80